/*
PART 4
*/


CREATE OR REPLACE PROCEDURE REPORT_SUMMARY_OF_ORDER (cur OUT SYS_REFCURSOR) (CUR OUT SYS_REFCURSOR)
AS
BEGIN

OPEN cur FOR SELECT 	DISTINCT
	REPLACE(SUBSTR(O.ORDER_REF, REGEXP_INSTR(O.ORDER_REF, '%[1-9]%'), LENGTH(O.ORDER_REF)),'-','') as ORDER_REF,
	UPPER(FORMAT (ORDER_DATE, 'MMM-yy')) AS ORDER_PERIOD,
	UPPER(SUBSTR(O.SUPPLIER_NAME, 1,1))+LOWER(SUBSTR(O.SUPPLIER_NAME,2,LENGTH(O.SUPPLIER_NAME))) as SUPPLIER_NAME,
	FORMAT(O.ORDER_TOTAL_AMOUNT,'#,0.00') as ORDER_TOTAL_AMOUNT,
	O.ORDER_STATUS,
	I.INVOICE_REFERENCE, 
	FORMAT(I.INVOICE_AMOUNT,'#,0.00') AS INVOICE_TOTAL_AMOUNT, 
CASE WHEN I.INVOICE_STATUS LIKE '%paid%' THEN	'OK'
	WHEN I.INVOICE_STATUS LIKE '%pending%' THEN 'To follow up'
	WHEN I.INVOICE_STATUS IS NULL THEN'To verify'
	ELSE 'error' END AS INVOICE_STATUS


FROM ORDER_DETAILS AS O, INVOICE_DETAILS AS I 

where O.SUPPLIER_NAME = I.SUPPLIER_NAME

ORDER BY ORDER_PERIOD DESC

END;

EXECUTE IMMEDIATE  REPORT_SUMMARY_OF_ORDER;