/*
PART 5
*/


CREATE OR REPLACE PROCEDURE THIRD_HIGHEST_ORDER_TOTAL_AMOUNT (cur OUT SYS_REFCURSOR) (CUR OUT SYS_REFCURSOR)
AS

BEGIN


OPEN cur FOR SELECT DISTINCT 
	REPLACE(SUBSTR(O.ORDER_REF, REGEXP_INSTR(O.ORDER_REF, '%[1-9]%'), LENGTH(O.ORDER_REF)),'-','') as ORDER_REF,
	TO_CHAR(O.ORDER_DATE, 'MM') + SUBSTR(TO_CHAR  (O.ORDER_DATE, 107), GREATEST(-LENGTH(TO_CHAR(VARCHAR(12),  (O.ORDER_DATE, 107)), -9)) AS ORDER_DATE,
	UPPER(O.SUPPLIER_NAME) as SUPPLIER_NAME,
	FORMAT(O.ORDER_TOTAL_AMOUNT,'#,0.00') as ORDER_TOTAL_AMOUNT,
	O.ORDER_STATUS,

	STUFF(
	(	SELECT DISTINCT ', ' + d.INVOICE_REFERENCE 
		FROM INVOICE_DETAILS as d
		WHERE d.SUPPLIER_NAME = I.SUPPLIER_NAME
		GROUP BY d.INVOICE_REFERENCE
		 FOR XML FROM dual PATH('')), 1, 2, ''

	) AS INVOICE_REFERENCE


FROM ORDER_DETAILS AS O, INVOICE_DETAILS AS I 

where O.SUPPLIER_NAME = I.SUPPLIER_NAME
AND 2=(
	SELECT COUNT(DISTINCT(O1.ORDER_TOTAL_AMOUNT))
	FROM ORDER_DETAILS O1
	WHERE O1.ORDER_TOTAL_AMOUNT > O.ORDER_TOTAL_AMOUNT
)

END;

EXECUTE IMMEDIATE  THIRD_HIGHEST_ORDER_TOTAL_AMOUNT;