/*
PART 2 
*/
CREATE USER SUPPLIER IDENTIFIED BY SUPPLIER
GO
CREATE TABLE [dbo].[SUPPLIER_GENERAL_DETAILS](

	SUPPLIER_NAME Varchar2(100) NOT NULL,
	SUPPLIER_CONTACT_NAME Varchar2(100) NOT NULL,
	SUPPLIER_ADDRESS Varchar2(200) NOT NULL,
	SUPPLIER_CONTACT_NUMBER Varchar2(50) NOT NULL,
	SUPPLIER_EMAIL Varchar2(320) NOT NULL,
	PRIMARY KEY(SUPPLIER_NAME)
)

CREATE TABLE [dbo].[INVOICE_DETAILS](
	INVOICE_REFERENCE Varchar2(100) NULL,
	INVOICE_DATE date NULL,
	INVOICE_DESCRIPTION Varchar2(200) NULL,
	INVOICE_AMOUNT Number(10, 2) NULL,
	INVOICE_STATUS Varchar2(10) NULL,
	INVOICE_HOLD_REASON Varchar2(100) NULL,
	SUPPLIER_NAME Varchar2(100) NULL,
	FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER_GENERAL_DETAILS(SUPPLIER_NAME)	
	
) 

CREATE TABLE [dbo].[ORDER_DETAILS](
	ORDER_REF Varchar2(100) NOT NULL,
	ORDER_DATE date NOT NULL,
	ORDER_DESCRIPTION Varchar2(200) NOT NULL,
	ORDER_TOTAL_AMOUNT Number(10, 2) NULL,
	ORDER_STATUS Varchar2(10) NOT NULL,
	ORDER_LINE_AMOUNT Number(10, 2) NULL,
	SUPPLIER_NAME Varchar2(100) NOT NULL,
	FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER_GENERAL_DETAILS(SUPPLIER_NAME)
) 