/*
PART 3
*/


CREATE OR REPLACE PROCEDURE UPLOAD_DETAILS
AS
BEGIN

-- Inserting details in 'SUPPLIER_GENERAL_DETAILS' table, 
-- since phone numbers do not have letters a where option has been set up which eliminates the letters 

    INSERT INTO SUPPLIER_GENERAL_DETAILS (SUPPLIER_NAME, SUPPLIER_CONTACT_NAME, SUPPLIER_ADDRESS, SUPPLIER_CONTACT_NUMBER,SUPPLIER_EMAIL) 
        SELECT DISTINCT SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER,SUPP_EMAIL
        FROM XXBCM_ORDER_MGT WHERE SUPP_CONTACT_NUMBER NOT LIKE '%[a-z]%'

--Inserting details in 'ORDER_DETAILS' table
-- converting date into relevant format
-- convert varchar to decimal format

	INSERT INTO ORDER_DETAILS (ORDER_REF,ORDER_DATE,ORDER_DESCRIPTION,ORDER_TOTAL_AMOUNT,ORDER_STATUS,ORDER_LINE_AMOUNT,SUPPLIER_NAME)
	SELECT ORDER_REF,convert(date, order_date ,103) FROM dual as StringToDate,ORDER_DESCRIPTION,try_cast(NVL(NULLIF(ORDER_TOTAL_AMOUNT, ''),0) AS DECIMAL(12,2)),
	ORDER_STATUS,try_cast(NVL(NULLIF(ORDER_LINE_AMOUNT, ''),0) AS DECIMAL(12,2)),SUPPLIER_NAME
	FROM XXBCM_ORDER_MGT

--Inserting details in 'INVOICE_DETAILS' table

	INSERT INTO INVOICE_DETAILS (INVOICE_REFERENCE,INVOICE_DATE,INVOICE_DESCRIPTION,INVOICE_AMOUNT,INVOICE_STATUS,INVOICE_HOLD_REASON,SUPPLIER_NAME)
	SELECT INVOICE_REFERENCE,convert(date, INVOICE_DATE ,103) FROM dual AS INVOICE_DATE_STRING,
	INVOICE_DESCRIPTION,try_cast(NVL(NULLIF(INVOICE_AMOUNT, ''),0) AS DECIMAL(12,2)),INVOICE_STATUS,INVOICE_HOLD_REASON,SUPPLIER_NAME
	FROM XXBCM_ORDER_MGT
END;

EXECUTE IMMEDIATE  UPLOAD_DETAILS;