/*
PART 6
*/

/* FUNCTION TO REMOVE ALL THE SPECICIAL CHARACTERS IN PHONENUMBER  AND SET Character - in phone number
**/


CREATE OR REPLACE FUNCTION GET_NUMERIC_PHONE_NUMBER
(  @string_phone_number VARCHAR2)
RETURN VARCHAR2
AS
  @intphone NUMBER(10)
  BEGIN
@intphone := REGEXP_INSTR(@string_phone_number, '%[^0-9]%')
  BEGIN
    WHILE @intphone > 0
    LOOP
      @string_phone_number := STUFF(@string_phone_number, @intphone, 1, '' )
      @intphone := REGEXP_INSTR(@string_phone_number, '%[^0-9]%' )
    END LOOP
  END
  RETURN reverse(stuff(NVL(reverse(@string_phone_number),0),5,0,'-'))
END;
GO

/* PROCEDURE CREATION
**/


CREATE OR REPLACE PROCEDURE LIST_OF_SUPPLIERS (cur OUT SYS_REFCURSOR) (CUR OUT SYS_REFCURSOR)
AS
BEGIN


OPEN cur FOR SELECT
	S.SUPPLIER_NAME,
	S.SUPPLIER_CONTACT_NAME,
	CASE
	
	WHEN SUPPLIER_CONTACT_NUMBER = NULL THEN 'null'
	WHEN SUPPLIER_CONTACT_NUMBER LIKE '%,%' THEN 
	dbo.GET_NUMERIC_PHONE_NUMBER(
	SUBSTR(SUPPLIER_CONTACT_NUMBER, 1, INSTR(SUPPLIER_CONTACT_NUMBER, ',', INSTR(SUPPLIER_CONTACT_NUMBER, ',')) - 1))
	ELSE dbo.GET_NUMERIC_PHONE_NUMBER(SUPPLIER_CONTACT_NUMBER)
	END AS Supplier_Contact_No_1,

	CASE
	WHEN SUPPLIER_CONTACT_NUMBER = NULL THEN 'null'
	WHEN SUPPLIER_CONTACT_NUMBER LIKE '%,%' THEN 	
	dbo.GET_NUMERIC_PHONE_NUMBER(SUBSTR(SUPPLIER_CONTACT_NUMBER, GREATEST(-LENGTH(SUPPLIER_CONTACT_NUMBER), -INSTR(REVERSE, ','(SUPPLIER_CONTACT_NUMBER), INSTR(REVERSE, ','(SUPPLIER_CONTACT_NUMBER))) -1)))
	ELSE ''
	END AS Supplier_Contact_No_2,


	COUNT(DISTINCT O.ORDER_REF) AS Total_Orders,
	FORMAT(SUM(O.ORDER_TOTAL_AMOUNT),'#,0.00') AS Order_Total_Amount

FROM SUPPLIER_GENERAL_DETAILS AS S, ORDER_DETAILS AS O

WHERE (O.SUPPLIER_NAME = S.SUPPLIER_NAME) AND (O.ORDER_DATE BETWEEN '2017-01-01' AND '2017-08-31')

GROUP BY S.SUPPLIER_NAME,S.SUPPLIER_CONTACT_NAME,S.SUPPLIER_CONTACT_NUMBER

END;

EXECUTE IMMEDIATE  LIST_OF_SUPPLIERS;